name: Python Code Review and Security Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out repository code

      # Python sürümünü ayarla
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Python 3.11 kullan

      # Bağımlılıkları kur
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Kod stilini kontrol et (flake8)
      - name: Lint with flake8
        run: |
          # .flake8 yapılandırması kök dizinde olabilir
          flake8 ./ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ./ --count --max-complexity=10 --max-line-length=127 --statistics

      # Güvenlik taraması yap (Bandit)
      - name: Security check with Bandit
        run: |
          bandit -r ./
